import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {UserProvider, useUser} from '../AuthContext/useContext'
import { Toaster } from "sonner";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider >
      <Toaster />
      <body className='antialiased bg-violet-100'>{children}</body>
      </UserProvider>
    </html>
  )
}
